name: IPTV M3U Generator

on:
  schedule:
    - cron: '0 0 * * *'  # 每天凌晨执行
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Check Pipfile format
        run: |
          if [ -f "Pipfile" ]; then
            echo "Checking Pipfile format..."
            pip install toml
            python -c "import toml; toml.load(open('Pipfile'))"
            if [ $? -eq 0 ]; then
              echo "Pipfile format is valid."
            else
              echo "Pipfile format is invalid. Please check the file."
              exit 1
            fi
          else
            echo "Pipfile not found."
            exit 1
          fi

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install --deploy

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Generate M3U and TXT files
        run: pipenv run dev

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/result.m3u output/result.txt
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update IPTV files"
            git push
          fi    
